### PR TITLE
Simplify report dependency

### PR DESCRIPTION
**Pull request by liuzhenqi77**
Hi, I happened to notice that the report page is referencing a large number of locally-stored css/js files (including 1500+ fontawesome svg files and duplicated non-minified js). I found that they could easily cause slow copy/archive operations and transmission from HPC to local (since globus does not support recursively following symlinks). I was wondering is there a reason why CDN-based js/css were not used? Here's a draft change showing the idea roughly (looks fine but not tested for all report functions), please feel free to change. Thanks!

### CODE REVIEW

**Comment by liuzhenqi77** [comment]
I basically made two changes as detailed below. I tested with a custom-built singularity container and it seems to be working fine.
However, as I'm not familiar with original design and complete functions of the qc webpage, this is only a suggestion, please feel free to modify & review the changes. Thank you!

1) replacing several js/css files with cdn links (including bootstrap, fontawesome, datatables, bootstrap-multiselect, ekko-lightbox, select2, jquery, etc) in `dmriqcpy/template/index.html`, this would greatly reduce number of files (previously each individual report has 1.5k+ files due to fontawesome svg), and speed up cp/tar/globus operations. I wasn't sure about the remaining js/css files so I didn't change them.

2) adding `include_plotlyjs=False` to all `plotly.offline.plot()` functions in `dmriqcpy/viz/graph.py`, and adding cdn link for plotly js in `dmriqcpy/template/index.html`. It seems plotly is including the js file for each plot included in the webpage, making it very large (3MB+ for each plot). For example, this would reduce `report_dti.html` from 17MB+ to 100kB+.

Note that after the change it would require internet connection when viewing the webpage.

**Comment by arnaudbore** [comment]
Hi @liuzhenqi77 ,
I talked a little bit with @GuillaumeTh and we agreed. This PR is really interesting but we would like to keep the current behavior as default. 
"Your way" could be activated using a variable --online. 
What do you think ? 
Do you have some time to workin on this ?

In the next weeks we would like to release a version with this feature.
Thank you again for this work.

**Comment by liuzhenqi77** [comment]
Hi I'm glad this feature could be of help! 
It seems several layers and many files (scripts, report and plotting functions) need to be changed to pass this argument correctly, and I'm not super familiar with the internal organization, so I'm afraid I may not have enough time in the coming weeks to make the changes in time for the release.

(Although I might not be able to work on this soon. If you were concerning offline use, one alternative solution I would suggest other than passing the argument is to keep all js/css online by default, and make the webpages possible to [fallback to local stylesheet](https://stackoverflow.com/questions/7383163/how-to-fallback-to-local-stylesheet-not-script-if-cdn-fails). So the files could be safely removed.)

**Comment by arnaudbore** [comment]
Oh I think you misunderstood my point. We could have two different template and depending on how you call the scripts (with or without the option --offline) it would use one or the other template. What do you think ?

**Comment by liuzhenqi77** [comment]
Thank you for the clarification. That makes sense! 
I could try working on this in the coming weeks if I have time.

**Comment by arnaudbore** [comment]
I'm thinking about releasing a new version by the end of next week. If you're not able to make it, I'll push a new PR that will mimic yours.

**Comment by liuzhenqi77** [comment]
Sure sounds good! Thank you.

**Comment by arnaudbore** [comment]
Just suggested a new PR #48 which takes everything  @liuzhenqi77 coded + extension with an arg for each function.

**Pull request closed without merging**
